Remove Salt from installed packages
It is pulling in ZeroMQ libraries that are causing conflicts during a
yum update:

    Resolving Dependencies
    --> Running transaction check
    ---> Package zeromq.x86_64 0:4.0.5-4.el7 will be updated
    --> Processing Dependency: libzmq.so.4()(64bit) for package: python-zmq-14.7.0-2.el7.x86_64
    ---> Package zeromq.x86_64 0:4.1.4-5.el7 will be an update
    --> Processing Dependency: libsodium.so.13()(64bit) for package: zeromq-4.1.4-5.el7.x86_64
    --> Running transaction check
    ---> Package libsodium.x86_64 0:1.0.5-1.el7 will be installed
    ---> Package zeromq.x86_64 0:4.0.5-4.el7 will be updated
    --> Processing Dependency: libzmq.so.4()(64bit) for package: python-zmq-14.7.0-2.el7.x86_64
    --> Finished Dependency Resolution
    Error: Package: python-zmq-14.7.0-2.el7.x86_64 (@centos-openstack-newton)
	   Requires: libzmq.so.4()(64bit)
	   Removing: zeromq-4.0.5-4.el7.x86_64 (@centos-openstack-newton)
	       libzmq.so.4()(64bit)
	   Updated By: zeromq-4.1.4-5.el7.x86_64 (epel)
	      ~libzmq.so.5()(64bit)
     You could try using --skip-broken to work around the problem
     You could try running: rpm -Va --nofiles --nodigest

Eventually we will want to fix the underlying package conflict.